baseURL = "/"
languageCode = "en-us"
title = "Social Futures Lab Blog"
theme = "anubis2"

[pagination]
pagerSize = 5

[params.author]
name = "Social Futures Lab"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Blog"
identifier = "blog"
url = "/posts/"
weight = 4

[[menu.main]]
name = "Media"
identifier = "media"
url = "/media/"
weight = 5

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
